# Generated by Django 4.2.7 on 2023-11-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0002_rename_note_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='title',
            new_name='adress',
        ),
        migrations.AddField(
            model_name='sign',
            name='classification',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign',
            name='view',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
