# Generated by Django 4.2.7 on 2023-11-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0003_rename_title_sign_adress_sign_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
