# Generated by Django 4.2.7 on 2023-11-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0004_sign_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='latitude',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sign',
            name='longitude',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
